"""initial schema

Revision ID: fbf02a6e4764
Revises: 
Create Date: 2026-09-03 03:40:32.031824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fbf02a6e4764'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_type', sa.Enum('user', 'ai_agent', name='actor_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('default_standards_profile', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('resource', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('test_design_technique',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('istqb_chapter_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_level',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('test_type',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('standards_profile', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_project_org_name')
    )
    op.create_index(op.f('ix_project_org_id'), 'project', ['org_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_org_id'), 'role', ['org_id'], unique=False)
    op.create_table('user',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ai_agent',
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('model_or_provider', sa.String(), nullable=True),
    sa.Column('mcp_session_ref', sa.String(), nullable=True),
    sa.Column('acting_on_behalf_of_user_id', sa.Uuid(), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['acting_on_behalf_of_user_id'], ['user.actor_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('actor_id')
    )
    op.create_table('auth_identity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('local', 'oidc', 'saml', 'ldap', 'github', 'google', name='auth_provider'), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.actor_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_identity_user_id'), 'auth_identity', ['user_id'], unique=False)
    op.create_table('environment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_project_id'), 'environment', ['project_id'], unique=False)
    op.create_table('org_membership',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('invited', 'active', 'suspended', name='org_membership_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['user.actor_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'user_id', name='uq_org_membership_org_user')
    )
    op.create_index(op.f('ix_org_membership_org_id'), 'org_membership', ['org_id'], unique=False)
    op.create_index(op.f('ix_org_membership_user_id'), 'org_membership', ['user_id'], unique=False)
    op.create_table('refresh_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.actor_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.create_table('release',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('version_label', sa.String(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_project_id'), 'release', ['project_id'], unique=False)
    op.create_table('requirement',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_project_id'), 'requirement', ['project_id'], unique=False)
    op.create_table('role_assignment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['actor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['org_id'], ['organization.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actor_id', 'org_id', 'project_id', 'role_id', name='uq_role_assignment_actor_org_project_role')
    )
    op.create_index(op.f('ix_role_assignment_actor_id'), 'role_assignment', ['actor_id'], unique=False)
    op.create_index(op.f('ix_role_assignment_org_id'), 'role_assignment', ['org_id'], unique=False)
    op.create_table('role_permission',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permission_permission_id'), 'role_permission', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permission_role_id'), 'role_permission', ['role_id'], unique=False)
    op.create_table('test_plan',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('approach', sa.Text(), nullable=True),
    sa.Column('staffing_and_training', sa.Text(), nullable=True),
    sa.Column('schedule', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'approved', 'superseded', name='test_plan_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_actor_id'], ['actor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_plan_project_id'), 'test_plan', ['project_id'], unique=False)
    op.create_table('test_suite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suite_project_id'), 'test_suite', ['project_id'], unique=False)
    op.create_table('approval',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_plan_id', sa.Uuid(), nullable=False),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['user.actor_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_test_plan_id'), 'approval', ['test_plan_id'], unique=False)
    op.create_table('entry_exit_criteria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_plan_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('entry', 'exit', 'suspension', 'resumption', name='entry_exit_criteria_type'), nullable=False),
    sa.Column('condition_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plan.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entry_exit_criteria_test_plan_id'), 'entry_exit_criteria', ['test_plan_id'], unique=False)
    op.create_table('risk_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=True),
    sa.Column('test_plan_id', sa.Uuid(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('likelihood', sa.Enum('low', 'medium', 'high', name='risk_likelihood'), nullable=False),
    sa.Column('impact', sa.Enum('low', 'medium', 'high', name='risk_impact'), nullable=False),
    sa.Column('mitigation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('requirement_id IS NOT NULL OR test_plan_id IS NOT NULL', name='ck_risk_item_requirement_or_test_plan'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_condition',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='test_condition_priority'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_condition_requirement_id'), 'test_condition', ['requirement_id'], unique=False)
    op.create_table('test_cycle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_plan_id', sa.Uuid(), nullable=False),
    sa.Column('release_id', sa.Uuid(), nullable=False),
    sa.Column('environment_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['release_id'], ['release.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plan.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_cycle_test_plan_id'), 'test_cycle', ['test_plan_id'], unique=False)
    op.create_table('test_plan_test_suite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_plan_id', sa.Uuid(), nullable=False),
    sa.Column('test_suite_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_plan_id'], ['test_plan.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_plan_id', 'test_suite_id', name='uq_test_plan_test_suite')
    )
    op.create_index(op.f('ix_test_plan_test_suite_test_plan_id'), 'test_plan_test_suite', ['test_plan_id'], unique=False)
    op.create_index(op.f('ix_test_plan_test_suite_test_suite_id'), 'test_plan_test_suite', ['test_suite_id'], unique=False)
    op.create_table('requirement_test_condition_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('test_condition_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_condition_id'], ['test_condition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'test_condition_id', name='uq_requirement_test_condition_link')
    )
    op.create_index(op.f('ix_requirement_test_condition_link_requirement_id'), 'requirement_test_condition_link', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_test_condition_link_test_condition_id'), 'requirement_test_condition_link', ['test_condition_id'], unique=False)
    op.create_table('test_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_condition_id', sa.Uuid(), nullable=True),
    sa.Column('test_level_id', sa.Uuid(), nullable=False),
    sa.Column('test_type_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'reviewed', 'approved', 'deprecated', name='test_case_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_actor_id'], ['actor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_condition_id'], ['test_condition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_level_id'], ['test_level.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_type_id'], ['test_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('attachment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('url_or_path', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachment_test_case_id'), 'attachment', ['test_case_id'], unique=False)
    op.create_table('requirement_test_case_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requirement_id', 'test_case_id', name='uq_requirement_test_case_link')
    )
    op.create_index(op.f('ix_requirement_test_case_link_requirement_id'), 'requirement_test_case_link', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirement_test_case_link_test_case_id'), 'requirement_test_case_link', ['test_case_id'], unique=False)
    op.create_table('test_case_test_design_technique',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('test_design_technique_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_design_technique_id'], ['test_design_technique.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'test_design_technique_id', name='uq_test_case_test_design_technique')
    )
    op.create_index(op.f('ix_test_case_test_design_technique_test_case_id'), 'test_case_test_design_technique', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_case_test_design_technique_test_design_technique_id'), 'test_case_test_design_technique', ['test_design_technique_id'], unique=False)
    op.create_table('test_condition_test_case_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_condition_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_condition_id'], ['test_condition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_condition_id', 'test_case_id', name='uq_test_condition_test_case_link')
    )
    op.create_index(op.f('ix_test_condition_test_case_link_test_case_id'), 'test_condition_test_case_link', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_condition_test_case_link_test_condition_id'), 'test_condition_test_case_link', ['test_condition_id'], unique=False)
    op.create_table('test_execution',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_cycle_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('executed_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('result', sa.Enum('pass', 'fail', 'blocked', 'skipped', name='test_execution_result'), nullable=False),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_actor_id'], ['actor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_cycle_id'], ['test_cycle.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_execution_cycle_case', 'test_execution', ['test_cycle_id', 'test_case_id'], unique=False)
    op.create_index(op.f('ix_test_execution_test_case_id'), 'test_execution', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_execution_test_cycle_id'), 'test_execution', ['test_cycle_id'], unique=False)
    op.create_table('test_step',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'sequence', name='uq_test_step_case_sequence')
    )
    op.create_index(op.f('ix_test_step_test_case_id'), 'test_step', ['test_case_id'], unique=False)
    op.create_table('test_suite_test_case',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_suite_id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suite.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_suite_id', 'test_case_id', name='uq_test_suite_test_case')
    )
    op.create_index(op.f('ix_test_suite_test_case_test_case_id'), 'test_suite_test_case', ['test_case_id'], unique=False)
    op.create_index(op.f('ix_test_suite_test_case_test_suite_id'), 'test_suite_test_case', ['test_suite_id'], unique=False)
    op.create_table('defect',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_execution_id', sa.Uuid(), nullable=False),
    sa.Column('reported_by_actor_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='defect_severity'), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reported_by_actor_id'], ['actor.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_execution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_defect_test_execution_id'), 'defect', ['test_execution_id'], unique=False)
    op.create_table('test_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_execution_id', sa.Uuid(), nullable=False),
    sa.Column('logged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.Enum('status_change', 'comment', 'attachment', 'agent_action', name='test_log_event_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_execution_id'], ['test_execution.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_test_log_execution_logged_at', 'test_log', ['test_execution_id', 'logged_at'], unique=False)
    op.create_index(op.f('ix_test_log_test_execution_id'), 'test_log', ['test_execution_id'], unique=False)
    op.create_table('test_case_defect_link',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('test_case_id', sa.Uuid(), nullable=False),
    sa.Column('defect_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defect.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_case.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('test_case_id', 'defect_id', name='uq_test_case_defect_link')
    )
    op.create_index(op.f('ix_test_case_defect_link_defect_id'), 'test_case_defect_link', ['defect_id'], unique=False)
    op.create_index(op.f('ix_test_case_defect_link_test_case_id'), 'test_case_defect_link', ['test_case_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_case_defect_link_test_case_id'), table_name='test_case_defect_link')
    op.drop_index(op.f('ix_test_case_defect_link_defect_id'), table_name='test_case_defect_link')
    op.drop_table('test_case_defect_link')
    op.drop_index(op.f('ix_test_log_test_execution_id'), table_name='test_log')
    op.drop_index('ix_test_log_execution_logged_at', table_name='test_log')
    op.drop_table('test_log')
    op.drop_index(op.f('ix_defect_test_execution_id'), table_name='defect')
    op.drop_table('defect')
    op.drop_index(op.f('ix_test_suite_test_case_test_suite_id'), table_name='test_suite_test_case')
    op.drop_index(op.f('ix_test_suite_test_case_test_case_id'), table_name='test_suite_test_case')
    op.drop_table('test_suite_test_case')
    op.drop_index(op.f('ix_test_step_test_case_id'), table_name='test_step')
    op.drop_table('test_step')
    op.drop_index(op.f('ix_test_execution_test_cycle_id'), table_name='test_execution')
    op.drop_index(op.f('ix_test_execution_test_case_id'), table_name='test_execution')
    op.drop_index('ix_test_execution_cycle_case', table_name='test_execution')
    op.drop_table('test_execution')
    op.drop_index(op.f('ix_test_condition_test_case_link_test_condition_id'), table_name='test_condition_test_case_link')
    op.drop_index(op.f('ix_test_condition_test_case_link_test_case_id'), table_name='test_condition_test_case_link')
    op.drop_table('test_condition_test_case_link')
    op.drop_index(op.f('ix_test_case_test_design_technique_test_design_technique_id'), table_name='test_case_test_design_technique')
    op.drop_index(op.f('ix_test_case_test_design_technique_test_case_id'), table_name='test_case_test_design_technique')
    op.drop_table('test_case_test_design_technique')
    op.drop_index(op.f('ix_requirement_test_case_link_test_case_id'), table_name='requirement_test_case_link')
    op.drop_index(op.f('ix_requirement_test_case_link_requirement_id'), table_name='requirement_test_case_link')
    op.drop_table('requirement_test_case_link')
    op.drop_index(op.f('ix_attachment_test_case_id'), table_name='attachment')
    op.drop_table('attachment')
    op.drop_table('test_case')
    op.drop_index(op.f('ix_requirement_test_condition_link_test_condition_id'), table_name='requirement_test_condition_link')
    op.drop_index(op.f('ix_requirement_test_condition_link_requirement_id'), table_name='requirement_test_condition_link')
    op.drop_table('requirement_test_condition_link')
    op.drop_index(op.f('ix_test_plan_test_suite_test_suite_id'), table_name='test_plan_test_suite')
    op.drop_index(op.f('ix_test_plan_test_suite_test_plan_id'), table_name='test_plan_test_suite')
    op.drop_table('test_plan_test_suite')
    op.drop_index(op.f('ix_test_cycle_test_plan_id'), table_name='test_cycle')
    op.drop_table('test_cycle')
    op.drop_index(op.f('ix_test_condition_requirement_id'), table_name='test_condition')
    op.drop_table('test_condition')
    op.drop_table('risk_item')
    op.drop_index(op.f('ix_entry_exit_criteria_test_plan_id'), table_name='entry_exit_criteria')
    op.drop_table('entry_exit_criteria')
    op.drop_index(op.f('ix_approval_test_plan_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_test_suite_project_id'), table_name='test_suite')
    op.drop_table('test_suite')
    op.drop_index(op.f('ix_test_plan_project_id'), table_name='test_plan')
    op.drop_table('test_plan')
    op.drop_index(op.f('ix_role_permission_role_id'), table_name='role_permission')
    op.drop_index(op.f('ix_role_permission_permission_id'), table_name='role_permission')
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_role_assignment_org_id'), table_name='role_assignment')
    op.drop_index(op.f('ix_role_assignment_actor_id'), table_name='role_assignment')
    op.drop_table('role_assignment')
    op.drop_index(op.f('ix_requirement_project_id'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_release_project_id'), table_name='release')
    op.drop_table('release')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_table('refresh_token')
    op.drop_index(op.f('ix_org_membership_user_id'), table_name='org_membership')
    op.drop_index(op.f('ix_org_membership_org_id'), table_name='org_membership')
    op.drop_table('org_membership')
    op.drop_index(op.f('ix_environment_project_id'), table_name='environment')
    op.drop_table('environment')
    op.drop_index(op.f('ix_auth_identity_user_id'), table_name='auth_identity')
    op.drop_table('auth_identity')
    op.drop_table('ai_agent')
    op.drop_table('user')
    op.drop_index(op.f('ix_role_org_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_project_org_id'), table_name='project')
    op.drop_table('project')
    op.drop_table('test_type')
    op.drop_table('test_level')
    op.drop_table('test_design_technique')
    op.drop_table('permission')
    op.drop_table('organization')
    op.drop_table('actor')
    # ### end Alembic commands ###
